[package]
name = "crate_b"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2021"

[dev-dependencies]
bolero = { path = "../../../lib/bolero" }

[[test]]
name = "fuzz_b"
path = "tests/fuzz_b/fuzz_target.rs"
harness = false
