[package]
name = "bolero-engine"
version = "0.4.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "fuzz and property testing framework"
homepage = "https://github.com/camshaft/bolero"
repository = "https://github.com/camshaft/bolero"
keywords = ["testing", "quickcheck", "property", "fuzz", "fuzzing"]
license = "MIT"
edition = "2018"
readme = "../README.md"

[features]
default = ["std", "rand", "panic_hook"]
std = ["alloc", "bolero-generator/std"]
alloc = ["bolero-generator/alloc"]
panic_hook = []

[dependencies]
bolero-generator = { version = "0.4", path = "../bolero-generator", default-features = false }
failure = "0.1"
lazy_static = "1"
rand = { version = "0.7", optional = true }

[dev-dependencies]
rand = "0.7"
